name: Atualizar Versão

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  versionamento:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositório
      uses: actions/checkout@v3

    - name: Instalar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Rodar script de versão
      run: python update_version.py

    - name: Commit automático da nova versão
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add version.txt README.md
        git commit -m "Atualiza versão automaticamente"
        git push